### ISSUE TITLE
Combined GemStone/Squeak/Pharo tests - revisited

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#105]
In Issue #29, I mentioned that I would eventually need this feature and at the time I figured that I could handle this requirement in GsDevKit_home and @fniephaus  [postulated that the following could be used to run the tests from travis](https://github.com/hpi-swa/smalltalkCI/issues/29#issuecomment-174314664):

```yml
script:
  - $SMALLTALK_CI_HOME/run.sh
  - $SMALLTALK_CI_HOME/run.sh -s Pharo-5.0
  - $SMALLTALK_CI_HOME/run.sh -s Squeak-5.0
```

However as I [get into this in earnest](https://github.com/GsDevKit/GsDevKit_home/issues/93), I am finding that things are not quite that simple.

To start with, here are the GsDevKit_home scripts that I'm using to create a Pharo client with the [GemStone-GCI](https://github.com/GsDevKit/GemStone-GCI) project loaded (**NOTE: I am starting to use the `smalltalk.ston` file for more than just travis!!!**):

```
    createClient -t pharo gciClient -v Pharo-5.0 -s $GS_HOME/sys/local/pharo/gciClient.ston # create the client with GemStone-GCI loaded
    startClient gciClient  # bring up the gciClient image ...
```

The file `$GS_HOME/sys/local/pharo/gciClient.ston` is basically the [.smalltalk.ston file for GemStone-GCI](https://github.com/GsDevKit/GemStone-GCI/blob/master/.smalltalk.ston), however, note that the `smalltalk.ston` file is **not** located in the GemStone-GCI git checkout.

I actually have the above creation scripts "working", but I have to use the `.smalltalk.ston` file from the GemStone-GCI project to do the load ... and of course the tests are run as well because I have to use **SmalltalkCI class>>runCIFor:** -- it would be much more convenient if  the creation protocol were a bit more diverse with the following additions to the class-side api:
- runCIFor:projectDirectory: - run the CI file from one path and use the specified proejct directory
- loadCIFor:projectDirectory: - execute the #loading directives only (I.e. just load the code and don't run tests)
- testCIFor: - execute only the #testing directive and assume that code is already loaded

I expect that the [GemStone-GCI `.travis.yml` file](https://github.com/GsDevKit/GemStone-GCI/blob/master/.travis.yml) will eventually look like the following and allow me to test different combinations of clients and GemStone versions:

```yml
language: smalltalk
sudo: false

os:
  - linux
  - osx

env:
  - GSCI_CLIENT=Pharo-5.0
  - GSCI_CLIENT=Pharo-4.0
  - GSCI_CLIENT=Pharo-3.0

smalltalk:
  - GemStone-3.2.13
  - GemStone-3.3.0

cache:
  directories:
    - $SMALLTALK_CI_CACHE
```

This will also take some monkey business in the `gemstone/run.sh` implementation.

I also have some proposals for extensions to the `smalltalk.ston` fields, but that will come in a separate message

**Comment by fniephaus** [comment]
SGTM and great that there already is a second use-case for smalltalkCI config files :)
I have one suggestion at the moment: You are using `env`s as a variation point which is ok, but I'd like to avoid the use of too many env vars if possible. One idea that I haven't worked on yet is that one could also specify a STON config for a build just like it's for example possible to [specify gem files in Ruby on Travis](https://docs.travis-ci.com/user/languages/ruby#Testing-against-multiple-versions-of-dependencies). So your example could look something like this:

```yml
language: smalltalk
sudo: false

os:
  - linux
  - osx

smalltalk_config:
  - smalltalk_pharo-5.0.ston
  - smalltalk_pharo-4.0.ston
  - smalltalk_pharo-3.0.ston

smalltalk:
  - GemStone-3.2.13
  - GemStone-3.3.0

cache:
  directories:
    - $SMALLTALK_CI_CACHE
```

This would mean that the client selection is encoded in the STON config which I think would make sense. What do you think? I guess I could start working on it if this would help here.
