### ISSUE TITLE
Ability to specify smalltalkCI STON config per build

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#106]
Currently, the default config name is `.smalltalk.ston` or `smalltalk.ston` and a user can overwrite `script` in the `.travis.yml` like this in order to use a custom name:
```yml
script: $SMALLTALK_CI_HOME/run.sh .my_custom_name.ston
```

It'd be cool to be able to specify the STON config per build just like it's possible to [specify a gem file for Ruby builds on Travis](https://docs.travis-ci.com/user/languages/ruby#Testing-against-multiple-versions-of-dependencies). Here's a simple example:

```yml
language: smalltalk
sudo: false

smalltalk_config:
  - smalltalk.ston
  - smalltalk_legacy.ston

smalltalk:
  - Pharo-5.0
  - Squeak-5.0
```

This new `smalltalk_config` key should accept a single value or a list (like above) and it should be part of the matrix expansion which means that the above would start 4 builds.

@bahnfahren, @chistopher, @jchromik, and @Nef10:
how much work would that be? Let me know if you want to work on this ;)

This might be useful for #105.
