### ISSUE TITLE
Selective dependency cache clear and/or selctive disabling for cetain platforms?

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#121]
A `.travis.yml` level option for selectively clearing/disabling the dependency cache would be useful. 

For platform versions like Pharo-5.0 and Squeak-trunk (I think) that are under constant development it does not make much sense to cache the image and vm, because a) you have no idea which version of image and vm were cached and b) you are never using the current version.

For GemStone, the bootstrapped extent is cached and periodically the code that contributes to the boostrapped extent is changed at which time it would be useful to clear the GemStone extents from the cache. This doesn't happen frequently, so clearing the entire travis cache would not be a travesty.

Now I know that one can arrange to control caches on a per platform basis:

``` yml
smalltalk:
  - Pharo-5.0\
  - Squeak-Trunk

matrix:
  include:
    - smalltalk: GemStone-3.2.12
      cache:
        directories:
          - $SMALLTALK_CI_CACHE
    - smalltalk: GemStone-3.1.0.6
      cache:
        directories:
          - $SMALLTALK_CI_CACHE
    - smalltalk: GemStone-3.3.0
      cache:
        directories:
          - $SMALLTALK_CI_CACHE
    - smalltalk: Squeak-4.4
      cache:
        directories:
          - $SMALLTALK_CI_CACHE
    - smalltalk: Squeak-4.0
      cache:
        directories:
          - $SMALLTALK_CI_CACHE
    - smalltalk: Pharo-4.0
      cache:
        directories:
          - $SMALLTALK_CI_CACHE
```

but then you lose the elegance of the standard .travis.yml that could look like the following:

``` yml
smalltalk:
  - GemStone-3.3.0
  - GemStone-3.2.12
  - GemStone-3.1.0.6
  - Pharo- 5.0
  - Pharo- 4.0
  - Squeak-Trunk
  - Squeak-4.0

env:
  - SMALLTALKCI_DISABLE_CACHE=" Pharo- 5.0 Squeak-Trunk"
cache:
  directories:
    - $SMALLTALK_CI_CACHE
```

Not a high priority, but more something to chew on ...
