### ISSUE TITLE
Easy support of other smalltalkCI version

### ISSUE THREAD

**Issue by Nef10** [hpi-swa/smalltalkCI#124]
It would be very handy if one you easily switch to another smalltalkCI version to test new features.
I really like what Travis CI uses for dpl: https://github.com/travis-ci/dpl/blob/master/TESTING.md
You just specify a branch and/or repo which will be used instead of the normal one in the `.travis.yml`:

```yaml
edge:
    source: myown/dpl
    branch: foo
```
