### ISSUE TITLE
How to tell which smalltalk_config is being used

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#128]
This [build](https://travis-ci.org/SeasideSt/Seaside/jobs/122655950) and this [build](https://travis-ci.org/SeasideSt/Seaside/jobs/122655949) were launched using different config files, but I can't tell which build is which by looking at travis ... 

In case it matters, here is the `.travis.yml` fille:

```
language: smalltalk
sudo: false

smalltalk:
  - Pharo-5.0
#  - Pharo-4.0
#  - Pharo-3.0
#  - Squeak-4.5
  - Squeak-5.0
#  - GemStone-3.1.0.6
#  - GemStone-3.2.14
  - GemStone-3.3.0

smalltalk_config: .smalltalk.ston

cache:
  directories:
    - $SMALLTALK_CI_CACHE

matrix:
  include:
    - smalltalk: 
        - GemStone-3.3.0
      smalltalk_config:
        - .smalltalk_gs_all.ston
```
