### ISSUE TITLE
Error: "No STON file named '[.smalltalk_gs_all.ston]' found in /home/travis/build/dalehenrich/Seaside", but file exists

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#129]
Here's the [log](https://travis-ci.org/dalehenrich/Seaside/jobs/122658242#L15) and here's the [file](https://github.com/dalehenrich/Seaside/blob/dkh-patch-1/.smalltalk_gs_all.ston) and here's the [.travis.yml](https://github.com/dalehenrich/Seaside/blob/dkh-patch-1/.travis.yml):

```yml
language: smalltalk
sudo: false

smalltalk:
  - Pharo-5.0
#  - Pharo-4.0
#  - Pharo-3.0
#  - Squeak-4.5
  - Squeak-5.0
#  - GemStone-3.1.0.6
#  - GemStone-3.2.14
  - GemStone-3.3.0

smalltalk_config: .smalltalk.ston

cache:
  directories:
    - $SMALLTALK_CI_CACHE

matrix:
  include:
    - smalltalk: 
        - GemStone-3.3.0
      smalltalk_config:
        - .smalltalk_gs_all.ston
```

not sure what's wrong...
