### ISSUE TITLE
dependencies not run when using an alternate smalltalk_config

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#138]
Note failed build in [voyage 7](https://travis-ci.org/dalehenrich/voyage/builds/128739978). 

[7.1 has `installing dependencies`](https://travis-ci.org/dalehenrich/voyage/jobs/128739980#L107).

[7.4 does not have an `installing dependencies`](https://travis-ci.org/dalehenrich/voyage/jobs/128739983#L125)

It seems that [this should to work](https://travis-ci.org/dalehenrich/Tugrik#L110) ...

Perhaps the problem is that mongo is being started --- but it is started for normal run?

**Comment by dalehenrich** [comment]
[Switched to run build as main config](https://travis-ci.org/dalehenrich/voyage/builds/128742825) ... the failure is not due to missing 32 bit libs, but then I didn't start mongo either...

**Comment by dalehenrich** [comment]
[...and vms download correctly even when mongo is started](https://travis-ci.org/dalehenrich/voyage/builds/128743513) ... so the problem appears to be directly related to using an alternate config...
Here's the [.travis.yml for build 7](https://github.com/dalehenrich/voyage/blob/01fbdb3b83e3e8814d13e36769d15eb2af51bed1/.travis.yml) and [.travis.yml for build 10](https://github.com/dalehenrich/voyage/blob/bd23d81f81128da14449019c788e6380f75d4be2/.travis.yml)

**Comment by fniephaus** [comment]
In GemStone builds, dependencies are normally installed as part of "Preparing build for GemStone":
![image](https://cloud.githubusercontent.com/assets/2368856/15106959/030a8228-15cd-11e6-8939-23875405276e.png)
https://travis-ci.org/dalehenrich/Tugrik/builds/128728962#L110

However, this didn't happened for some reason in
https://travis-ci.org/dalehenrich/voyage/jobs/128739983#L125.

Investigating...

**Comment by fniephaus** [comment]
Here's the corresponding code:
https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/smalltalk.rb#L190-L201

I believe the only reason why dependencies weren't installed has to be that  `$(lsb_release -cs)` was neither `precise` nor `trusty` which is odd. The "Build system information" in the following builds seem identical system-wise. Both use a Precise image.
https://travis-ci.org/dalehenrich/voyage/jobs/128739983
https://travis-ci.org/dalehenrich/voyage/builds/128758358

Hopefully, this was just a weird one-off.

Your [latest build failed](https://travis-ci.org/dalehenrich/voyage/builds/128758358#L1365), because of a GsDevKit-related problem.
Please keep an eye on this problem and let me know if I can help to get `voyage` work with Travis.

**Comment by dalehenrich** [comment]
Actually the failure is due to a baseline error in voyage.

To work around the problem, I've switched from using a config in a matrix to using the config in the "main .travis.yml" ... the failures seem to be due to using an alternate config in a matrix ... once I get past the build issues and get tests running, I will set up a matrix and see if it fails again ...

**Comment by dalehenrich** [comment]
For reference here is a [build that is running tests cleanly - failing tests](https://travis-ci.org/dalehenrich/voyage/builds/128859656).

I'll try different configurations of travis to see if I can expose the bug again ... the set of tests being run in this build are not the full test set that is desired ...

**Comment by dalehenrich** [comment]
[This build illustrates the problem again - for Pharo this time](https://travis-ci.org/dalehenrich/voyage/builds/128864617):
- [15.1 fails](https://travis-ci.org/dalehenrich/voyage/jobs/128864618) because of a test failure 
- [15.2 fails](https://travis-ci.org/dalehenrich/voyage/jobs/128864619#L170) because 32 bit libraries for Pharo are missing

The common denominator is that the dependencies are not getting installed correctly when a matrix is used for the smalltalk_config:

```yml
language: smalltalk
sudo: false

smalltalk_config: .smalltalk_gemstone.ston
os:
  - linux
#  - osx
services: 
  - mongodb
smalltalk:
   - GemStone-3.3.0
#  - Pharo-5.0
#  - Pharo-4.0
#  - Pharo-3.0
env: GSCI_CLIENTS="Pharo-5.0"
matrix:
  include:
    - smalltalk: Pharo-5.0
      smalltalk_config: .smalltalk.ston
cache:
  directories:
    - $SMALLTALK_CI_CACHE
```

I'll try some other combos ...

**Comment by dalehenrich** [comment]
[16.2 still fails without mongo service](https://travis-ci.org/dalehenrich/voyage/jobs/128868358):

```yml
language: smalltalk
sudo: false

smalltalk_config: .smalltalk_gemstone.ston
os:
  - linux
#  - osx
#services: 
#  - mongodb
smalltalk:
   - GemStone-3.3.0
#  - Pharo-5.0
#  - Pharo-4.0
#  - Pharo-3.0
env: GSCI_CLIENTS="Pharo-5.0"
matrix:
  include:
    - smalltalk: Pharo-5.0
      smalltalk_config: .smalltalk.ston
cache:
  directories:
    - $SMALLTALK_CI_CACHE
```
