### ISSUE TITLE
smalltalk_config no longer working?

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#178]
[A build yesterday](https://travis-ci.org/dalehenrich/metacello-work/builds/143207601) ran correctly. Note that there are two builds per Smalltalk version:

![screenshot - 07082016 - 03 53 11 pm](https://cloud.githubusercontent.com/assets/623951/16703641/1fe86e42-4524-11e6-8985-514274f20177.png)

[a Build run an hour ago](https://travis-ci.org/dalehenrich/metacello-work/builds/143436058) only has one build per Smalltalk version:

![screenshot - 07082016 - 03 54 46 pm](https://cloud.githubusercontent.com/assets/623951/16703678/692261c6-4524-11e6-8d42-9ca436ff8b8a.png)

The [`.travis.yml` file](https://github.com/dalehenrich/metacello-work/blob/dev/.travis.yml) looks like the following: 

```yml
language: smalltalk
sudo: false

os:
  - linux

smalltalk:
  - GemStone-3.3.1
  - Pharo-5.0
  - Squeak-5.0
  - GemStone-2.4.8
  - GemStone-3.1.0.6
  - GemStone-3.2.15
  - Pharo-3.0
  - Pharo-4.0
  - Pharo-6.0
  - Squeak-4.5
  - Squeak-4.6
  - Squeak-trunk

smalltalk_config:
  - .smalltalkA.ston
  - .smalltalkB.ston

matrix:
  allow_failures:
    - smalltalk: Squeak-4.4
    - smalltalk: Squeak-4.5
    - smalltalk: Squeak-4.6
    - smalltalk: Squeak-5.0
    - smalltalk: Squeak-trunk
    - smalltalk: Pharo-6.0

cache:
  directories:
    - $SMALLTALK_CI_CACHE
```

Fortunately, I had a `.smalltalk.ston` file that specified the full test suite --- note that there are 900+ tests in the combined runs and that the results shown in travis are truncated, which is why the runs were split in the first place ...
