### ISSUE TITLE
smalltalkCI Configuration 1.0

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#20]
Currently, smalltalkCI requires environment variables to be set, because this is the way Travis builds run.

However, when running it locally, it is preferable to be able to use normal flags instead of environment variables (e.g. `--baseline=MyProject` or `--keep_open`).

**Comment by peteruhnak** [comment]
How about adding a small script that would read the local `.travis.yml` file? With the option to explicitly override them via flags or env vars. Although it may add an extra dependency (yaml parser).

-----Original Message-----

**Comment by fniephaus** [comment]
Very good idea! I will look into this.

**Comment by fniephaus** [comment]
I have found cross-platform compatible way to read the `.travis.yml` of a project and now I am wondering, how a "perfect" `.travis.yml` would look like.

I think I'd prefer to use `smalltalk_` as a prefix like this:
```yml
language: smalltalk
sudo: false
smalltalk:
  - Squeak-trunk
  - Pharo-stable
  ...
smalltalk_baseline: myProject
smalltalk_baseline_group: ...
smalltalk_packages: ...
smalltalk_tests: ...
```

What do you think @marceltaeumel, @peteruhnak, @estebanlm and @krono?

Happy holidays! :christmas_tree:

**Comment by krono** [comment]
What's your rationale for the prefix? It somehow seems redundant. Also `baseline` is not a Smalltalk idea per se but more a Metacello idea, so the prefix doesn't fit.

**Comment by fniephaus** [comment]
I just want to avoid any name clashes with Travis and it would make clear that these key value pairs are used by smalltalkCI only.
How about this:

```yml
language: smalltalk
sudo: false
smalltalk:
  - Squeak-trunk
  - Pharo-stable
  ...
smalltalk_config:
  - baseline: myProject
  - baseline_group: ...
  - packages: ...
  - tests: ...
```

**Comment by estebanlm** [comment]
I cannot respond big because I’m in a place with almost none internet, but in sum: I like the direction this is going :)

Esteban

**Comment by peteruhnak** [comment]
I also think having prefixes everywhere is superfluous, so I would prefer the nested variant.

Two questions/suggestions though:

1. why is "packages" named so? I find it confusing as it actually specifies directory path and not a packages list. Perhaps naming it `directory` or `packages_directory` would be more explanatory.

2. using underscore_case seems like a natural progression from bash, but camelCase may be more appropriate for smalltalk? E.g. `baselineGroup:`, `smalltalkConfig:`

**Comment by krono** [comment]
And continuing from 2. by @peteruhnak, I'll actually like dashed versions:
```yaml
smalltalk-configuration:
  - baseline: myProject
  - baseline-group: ...
```

Btw: we shouldn't abbreviate if possible, I think

**Comment by fniephaus** [comment]
Hi all,

Thanks for the comments! This is great!

@peteruhnak Regarding 1.: `directory` definitely is better and I changed it in the new drafts. I didn't come up with anything better when I built the very first version of smalltalkCI. That's why...

Regarding 2.: I do like the idea of using camelCase, because it looks more like Smalltalk, and I see why @krono likes dashes. But I would argue that we shouldn't endorse two different styles within the `.travis.yml`. Travis is mostly using short names and underscores, see e.g. here:
https://docs.travis-ci.com/user/customizing-the-build/#Breaking-the-Build

Here's a new draft with all options:
### Draft 2
```yml
smalltalk_configuration:
  - directory: "my_project_folder"
  - metacello:
    - baseline: "myProject"
    - baseline_group: "default"
  - builder_ci: false
  - tests: "BASELINE.*"               # Pharo only
  - force_update: false               # Squeak only
  - script: "customScript.st"         # Squeak only
  - exclude:                          # Squeak only
    - categories:
       - "MyExcludedCategory"
       ...
    - classes:
      - "MyExcludedClass"
      ...
```

We could also separate the configuration sections by Smalltalk dialect, e.g.:

### Draft 3
```yml
squeak:
  - directory: "my_project_folder"
  - metacello:
    - baseline: "myProject"
    - baseline_group: "default"
  - builder_ci: false
  - force_update: false               # Squeak only
  - script: "customScript.st"         # Squeak only
  - exclude:                          # Squeak only
    - categories:
       - "MyExcludedCategory"
       ...
    - classes:
      - "MyExcludedClass"
      ...

pharo:
  - directory: "my_project_folder"
  - metacello:
    - baseline: "myProject"
    - baseline_group: "default"
  - builder_ci: false
  - tests: "BASELINE.*"               # Pharo only

# Currently no options for gemstone builds
```

After looking at it once more, I'd actually prefer draft 3, because the options can be different for each dialect and I am afraid they always will be.

Also, I am not sure what @JoshK and Travis think about this. The idea is to load custom build options directly from the `.travis.yml` within our framework. This would allow us to re-use the config file, decrease the number of global environment variables and to maintain options without having to update [travis-build](https://github.com/travis-ci/travis-build).

**Comment by fniephaus** [comment]
If we use custom key value pairs instead of environment variables, it will not be possible to use different values within the build matrix. Here's an example that won't work:

```yaml
matrix:
  - include:
    - smalltalk: Squeak-trunk
      smalltalk_configuration:
        - directory: "squeak_subfolder"
    - smalltalk: Pharo-alpha
      smalltalk_configuration:
        - directory: "pharo_subfolder"
```

I think it makes sense to keep the possibility of using global environment variables, so in a scenario like the above one would need to use env variables.

**Comment by peteruhnak** [comment]
Why would that not work?

The json equivalent is

```json
{
  "matrix": [
    {
      "include": [
        {
          "smalltalk_configuration": [
            {
              "directory": "squeak_subfolder"
            }
          ], 
          "smalltalk": "Squeak-trunk"
        }, 
        {
          "smalltalk_configuration": [
            {
              "directory": "pharo_subfolder"
            }
          ], 
          "smalltalk": "Pharo-alpha"
        }
      ]
    }
  ]
}
```

which seems fine to me. (an array of configurations)

**Comment by peteruhnak** [comment]
I like the variant 4 probably the best (the one with matrix); having the dialect name as the configuration key seems strange to me, because users may have several versions of the same dialect (e.g. someone wants to test Pharo 4 and Pharo 5, etc.)

What I am also thinking of is having some sort of configuration baselines, so I could specify configuration for Pharo (as in the draft 3), and then I can override the values in the configuration matrix (as in the draft 4)

**Comment by fniephaus** [comment]
The reason why draft 4 does not work is that it is not trivial to determine which `smalltalk_configuration` should be used for a build.
Here's an example:
```yml
smalltalk:
  - Squeak-trunk
smalltalk_configuration: #1
  - directory: "foo"
matrix:
  - include:
    - os: osx
      smalltalk: Squeak-trunk
      smalltalk_configuration: #2
        - directory: "squeak_subfolder"
    - smalltalk: Squeak-trunk
      builder_ci: true
      smalltalk_configuration: #3
        - directory: "squeak_subfolder"
    - smalltalk: Pharo-alpha
      smalltalk_configuration:
        - directory: "pharo_subfolder"
```
This would result in four builds: `Squeak-trunk` 2xLinux + 1xOSX and `Pharo-alpha` 1xLinux.
Since smalltalkCI reads the `.travis.yml` independently, it also has to figure out for which build it is running. Let's just say we are currently building `Squeak-trunk` on OSX. smalltalkCI knows that `Squeak-trunk` is being processed. It now needs to find the corresponding `smalltalk_configuration` `#2`, but there are also `#1` and `#3` for `Squeak-trunk`. In order to do so, it'd need to check on which operating system this is running and if it is using builderCI or not.
This is just a very simple example, but this can easily become very complicated.

The best way to implement the above would be through Travis. But since we can't just push our code to Travis and since we wanted to reduce the number of environment variables, I would suggest that we should use something like draft 2. If someone requires a more complex build matrix, it's still possible to overwrite values using environment variables.

@peteruhnak if you have a better idea, please let me know!

**Comment by fniephaus** [comment]
@peteruhnak @krono @estebanlm @marceltaeumel 

Are we all ok with the direction of draft 2 for now or does anyone have any strong objections?
Specifying all Smalltalk-related build configurations under `smalltalk_configuration` shouldn't cause any name clashes and separates Travis-related and Smalltalk-related configuration.
Grouping `baseline` and `baseline_group` under `metacello` clarifies that a baseline is a Metacello idea.
In draft 5 below, I have tried to also separate Squeak and Pharo configuration options. I'd argue that there will always be different platform-specific options and this way, it should be more obvious to the user.

What do you think about this?

### Draft 5 (based on Draft 2)
```yml
smalltalk_configuration:
  - directory: "my_project_folder"
  - metacello:
    - baseline: "myProject"
    - baseline_group: "default"
  - builder_ci: false
  # Squeak only
  - squeak:
    - force_update: false
    - script: "customScript.st"
    - exclude:
      - categories:
         - "MyExcludedCategory"
         ...
      - classes:
        - "MyExcludedClass"
        ...
  # Pharo only
  - pharo:
    - tests: "BASELINE.*"
    # for more than one:
    - tests:
    -  "BASELINE1.*"
    -  "BASELINE2.*"
```

**Comment by peteruhnak** [comment]
I don't think that I entirely understand the reason for rejecting draft 4.

Because the `include:` list can be processed item by item, which is always a single dialect-dialect_config pair (and thus you always know which configuration goes with which dialect). And I don't really see how this differs in Draft 5.

So I suppose the question is whether we want to have just a list of pairs, or an actual multi-dimensional matrix, which none of the drafts proposes. Otherwise the actual content of the configuration (metacello, baseline, ...) looks good to me.

As for the matrix, we would need to distinguish two concepts:

1. structural configuration variations (this is especially significant across dialects, as they may need entirely different configs)
2. value variations
  * i.e. in many (most?) cases I want to run identical configuration but with different variables --- e.g. I have a project and I want to test it in Pharo 4 and 5 and I want to test branches master and development; the config will be identical, only different version of Pharo and my project will be downloaded

In fact as far as Pharo is concerned, 2. is the majority case for existing Jenkins CI builds here https://ci.inria.fr/pharo-contribution/

Most of them use the same script (I don't think that you can see the script if you don't have the account there)

```
# jenkins puts all the params after a / in the job name as well :(
export JOB_NAME=`dirname $JOB_NAME`

wget --quiet -O - get.pharo.org/$PHARO+$VM | bash

./pharo Pharo.image save $JOB_NAME --delete-old
./pharo $JOB_NAME.image --version > version.txt

REPO=http://smalltalkhub.com/mc/HardCodedRepository/$JOB_NAME/main
./pharo $JOB_NAME.image config $REPO ConfigurationOfSton --install=$VERSION
./pharo $JOB_NAME.image test --junit-xml-output "$JOB_NAME.*"

zip -r $JOB_NAME.zip $JOB_NAME.image $JOB_NAME.changes

# clean up the workspace to not occupy too much stale space on the slaves
rm -rf *.image *.changes
```

And then user specifies in the matrix only `$PHARO` (40, 50) and `$VERSION` (stable, bleedingEdge).

So all in all ideal scenario (from my POV) is to make the most common scenarios as trivial as possible while not restricting users that want more control.

**Comment by fniephaus** [comment]
I absolutely agree that we should make common scenarios as trivial as possible while not restricting "power users".

And sure, it'd be possible to progress item by item from `include:`. But then we would run the test suits on all platforms in all builds and that is not what we want.

The problem here I think is Travis' matrix expansion.

Here's an example:
```yml
smalltalk_configuration:
  - directory: "my_project_folder"
    metacello:
      baseline: "MyProject"

matrix:
  include:
    - smalltalk: "Pharo-alpha"
      smalltalk_configuration:
        metacello:
          baseline_group: "Pharo"
    - smalltalk: "Squeak-trunk"
      smalltalk_configuration:
        metacello:
          baseline_group: "Squeak"
````

What the user wanted in this case are two builds:

```yml
smalltalk: "Pharo-alpha"
smalltalk_configuration:
  - directory: "my_project_folder"
    metacello:
      baseline: "MyProject"
      baseline_group: "Pharo"
```
and 
```yml
smalltalk: "Squeak-trunk"
smalltalk_configuration:
  - directory: "my_project_folder"
    metacello:
      baseline: "MyProject"
      baseline_group: "Squeak"
```

The problem is that Travis has no idea what to do with any of the `smalltalk_configuration`s, because only smalltalkCI knows about it. But smalltalkCI has no idea about how Travis expanded the build matrix.

The only solid way, we can get this to work is to extend [travis-core](https://github.com/travis-ci/travis-core). But then we'd need to pass all parameters somehow to smalltalkCI. For exactly this, we have been using global environment variables, but by reading the `.travis.yml` within smalltalkCI we wanted to reduce the number of global env variables.

For the above example to work with draft 5, the user could do this instead:
```yml
smalltalk_configuration:
  - directory: "my_project_folder"
    metacello:
      baseline: "MyProject"

matrix:
  include:
    - smalltalk: "Pharo-alpha"
      env: BASELINE_GROUP="Pharo"
    - smalltalk: "Squeak-trunk"
      env: BASELINE_GROUP="Squeak"
````

Travis already knows how to expand `env` within `matrix.include` and smalltalkCI will use values from the  environment when they are available. What happens is that smalltalkCI loads `smalltalk_configuration` from the `.travis.yml` and then checks the environment for overrides.

I can't think of a better way to pass parameters from Travis to smalltalkCI and also, I am not sure if we really want to reimplement the same behavior that is already available for `env` if you know what I mean.

However, the most common scenario is probably this:

```yml
smalltalk:
  - "Pharo-alpha"
  - "Pharo-stable"

smalltalk_configuration:
  - directory: "my_project_folder"
    metacello:
      baseline: "MyProject"
      baseline_group: "default"
```
And this will exactly work as intended: two builds for alpha and stable with the same configuration.

I hope this all makes more sense now.

Happy New Year :tada:

**Comment by dalehenrich** [comment]
If it's not too late to put my $0.02 in, I'm looking specifically at the `metacello` specification:

```
smalltalk_configuration:
  - directory: "my_project_folder"
    metacello:
      baseline: "MyProject"
      baseline_group: "default"
```

The [common pattern for a Metacello load expression](https://github.com/GsDevKit/Magritte3/blob/master/.travis.yml) that I use is:

```Smalltalk
Metacello new
  baseline: 'MyProject';
  repository: '...';
  load: 'default'
```

So wouldn't it be more intuitive to do the following:

```
smalltalk_configuration:
  - directory: "my_project_folder"
    metacello:
      baseline: "MyProject"
      load: "default"
```

and hopefully [multiple names could be passed into the `load:` option](https://github.com/GsDevKit/Seaside31/blob/gs_master/.travis.yml):

```
smalltalk_configuration:
  - directory: "my_project_folder"
    metacello:
      baseline: "MyProject"
      load: "CI" "Swazoo" "Zinc" "FastCGI"
```

**Comment by fniephaus** [comment]
Nope, you're not too late :smile: and that's a good idea!
For multiple names you'd probably need to do this:
```yml
smalltalk_configuration:
  - directory: "my_project_folder"
    metacello:
      baseline: "MyProject"
      load:
        - "CI"
        - "Swazoo"
        - "Zinc"
        - "FastCGI"
```

Since I've started to work on #25, we'd also need to support this:

```yml
smalltalk_configuration:
  - directory: "my_project_folder"
    metacello:
      configuration: "MyProject"
      version: "#bleedingEdge"
```

**Comment by joshk** [comment]
Hey All,

Josh here from Travis.

I've read though all the ideas and thought I would give some thoughts as well. Please excuse my bullet points, I find them easier to convey unordered ideas.

I think it might be best not to have this information in the `.travis.yml` file. Instead using a similar pattern to Bundler which allows you to specify which `Gemfile` you want to use. This way you could have multiple `SmalltalkConfiguration` files and then Travis can run a job and export which file should be used.

This gives more flexibility than using the `.travis.yml` file, and means you are not bound to any changes we make either. 

I do understand the advantage of using the `.travis.yml` file, but I also see the disadvantage too.

One example disadvantage is that we are considering letting people using `travis.yml` instead of `.travis.yml`, this could mess with your logic.

Those are my two cents :)

**Comment by fniephaus** [comment]
Hi @joshk, thanks for joining the discussion.
I agree, it's probably best to just use a different file and specify the file within the `.travis.yml`.
This will solve most of the problems mentioned above and make our implementation more independent from Travis' code.

How about we call the file `.smalltalk.yml`, then we can get rid of the `smalltalk_configuration` key and do this:


### Draft 6
```yml
directory: "my_project_folder"

metacello:
  - baseline: "myProject"
  - load: "default"
  # or
  - configuration: "myProject"
  - version: "#stable"

squeak: # Squeak only
  - force_update: false
  - script: "customScript.st"
  - exclude:
    - categories:
       - "MyExcludedCategory"
       ...
    - classes:
      - "MyExcludedClass"
      ...

pharo: # Pharo only
  - tests: "BASELINE.*"
  # for more than one:
  - tests:
    - "BASELINE1.*"
    - "BASELINE2.*"

gemstone: # GemStone only
  #nothing here yet

builder_ci: false
```

Thoughts?

**Comment by dalehenrich** [comment]
At this point it's probably worth mentioning that for **tODE**, I've introduced the notion of a [TDProjectEntryDefinition](https://github.com/dalehenrich/tode/blob/master/repository/Topez-Server-Core.package/TDProjectEntryDefinition.class/properties.json) that includes information over and above what is strictly needed for `Metacello`. Here is an example of a `TDProjectSpecEntryDefinition` for a `Sample` project (this one is for a baseline but here is a [configuration-based example](https://github.com/GsDevKit/GsDevKit_home/blob/gh-pages/XMLSupport.ston)):

```ston
TDObjectGatewayLeafNode{#name:'Sample',#contents:'^ TDProjectSpecEntryDefinition new
    comment: \'\';
    projectUrl: \'https://github.com/dalehenrich/sample\';
    baseline: \'Sample\'
      repository: \'github://dalehenrich/sample:master/repository\'
      loads: #(\'Core\');
    installScript: \'project clone --https --local Sample
      mount @/_home/shared/repos/sample/tode /home sample\';
    gitCheckout: \'master\';
    status: #(#\'inactive\');
    locked: false;
    yourself'}`
```

The `installScript` field includes instructions for installing the project in **tODE**, but one can imagine including additional fields for Squeak/Pharo/GemStone/tODE/smalltalkCI ...

As I think about this, it would be simpler if there were a single file/object embedded in a github project that was used by more than just travis  ... I've found this approach very useful for tODE (which is why I created this [web site for tOIDE project entries](http://gsdevkit.github.io/GsDevKit_home/)) but I can definitely imagine that such files/objects would be useful for loading/managing Metacello-based projects in all Smalltalk dialects ...

I am biased towards objects and I'm not aware of a Smalltalk implementation for YAML, so a smalltalkCI.yml wouldn't be useful beyond the travis context ...

**Comment by joshk** [comment]
You could still add something to the `.travis.yml` which allows you to specify the Smalltalk config file, incase you want to run two different configs for builds (if you use matrix.include), or just specify a Travis specific config, like below:
```
language: smalltalk
sudo: false
smalltalk:
  - Squeak-trunk
  - Pharo-stable
smalltalk_config: .smalltalk-travis.yml

**Comment by joshk** [comment]
The `smalltalk_config` value could either be something we pass in when we generate the build script, or an env var we set.

**Comment by dalehenrich** [comment]
@fniephaus, regarding the info in the [configuration-based smalltalk_configuration](https://github.com/hpi-swa/smalltalkCI/issues/20#issuecomment-168541208):

```yml
smalltalk_configuration:
  - directory: "my_project_folder"
    metacello:
      configuration: "MyProject"
      version: "#bleedingEdge"
```

Is there a reason why you haven't included a `load:` field there as well? For `Metacello` the load applies equally to baselines or configurations so:

```yml
smalltalk_configuration:
  - directory: "my_project_folder"
  - metacello:
      - configuration: "MyProject"
      - version: "#bleedingEdge"
      - load: 'default"
```

would make sense ...

**Comment by fniephaus** [comment]
@dalehenrich I see your point regarding the yml file and if we decide to split the config from the `.travis.yml`, we are free to choose how we want to specify builds. If we want to specify everything in e.g. a Smalltalk file, we still need to parse the information somehow and make it available in the bash script.
I have the feeling that for this we need to write a lot of boilerplate code without benefiting too much.
Let me as the question what one would do with the Metacello configuration for Travis other than using it for Travis?

On the other hand, we could also simplify smalltalkCI's options by letting the user define Smalltalk code for each, to load and to run the project of interest. This would make smalltalkCI independent from Metacello.

I believe there's no other popular format that is supported out-of-the-box in all dialects, right? `JSON` for example isn't and I wouldn't really want `XML`.

Regarding your [latest comment](https://github.com/hpi-swa/smalltalkCI/issues/20#issuecomment-168549336): yes, `load` applies to baselines and configurations, my example just wasn't complete I guess :smiley:

**Comment by fniephaus** [comment]
@joshk of course, we need to add something that specifies the new configuration file in the `.travis.yml`.
By "something we pass in" you meant that we could do something like
```bash
sh.cmd "$SMALLTALK_CI_HOME/run.sh" "#{config[:smalltalk_configuration].to_s}"
```
instead of just [this](https://github.com/travis-ci/travis-build/blob/4620532908f16eed80ab7e7d791687f001fbfccb/lib/travis/build/script/smalltalk.rb#L50)? Or is there any other common way (besides env vars) that we can use to pass values from Travis to smalltalkCI?

**Comment by dalehenrich** [comment]
@fniephaus regarding:

> what one would do with the Metacello configuration for Travis other than using it for Travis?

Wait, the BaselineOf for the project is shared by all dialects. Typically there is a readme that has dialect-specific smalltalk load code and the travis tests **ought** to be testing that the that workspace will work (at a minimum) ... If there were a file included in the project that was used by the developer and travis to perform to load the project regardless of dialect, then that would be very useful .... then when the *load instructions* change, only one place needs to be changed ... and if a developer customizes the *load instructions* she will get a git conflict to notify them that a key file is changed ...

So the advantage is that **there is no Metacello configuration for Travis**, there is just a single load configuration for all uses ...

**Comment by dalehenrich** [comment]
@fniephaus regarding:

> we could also simplify smalltalkCI's options by letting the user define Smalltalk code for each

I do think that `builderCI` has way too many moving parts and I like the fact that with smalltalkCI, one only need edit the .travisCI file to control *all facets of the travis build* and I would prefer not to lose that simplicity.

But ..... when it came up that a separate file would be needed, I was reminded of the fact that for GemStone/tODE I would probably prefer to reference the *project entry* for the project for travis builds for the reasons mentioned above: a single **object** that is shared by travis and all stones (in the case of GemStone) and when I change that **object** all of the stones sharing that object will see the change ...

Along these lines, I'm trying to figure out what the *dialect-specific* options mean. When I look at the following options I am left scratching my head trying to figure out what any of these settings would look like for Metacello (for example):

```yml
squeak: # Squeak only
  - force_update: false
  - script: "customScript.st"
  - exclude:
    - categories:
       - "MyExcludedCategory"
       ...
    - classes:
      - "MyExcludedClass"
      ...

pharo: # Pharo only
  - tests: "BASELINE.*"
  # for more than one:
  - tests:
    - "BASELINE1.*"
    - "BASELINE2.*"
```

For Squeak,  can guess what `force update` means, but why would I want to exclude classes and categories, if these exclusions apply to the list of classes derived from the baseline, whey would I want to have those options for Pharo and GemStone as well ... 

For Pharo, I can't even guess what the tests option means .... what is a `BASELINE.*`? ... Again if it is useful for Pharo, would it not be useful for Squeak and GemStone ...

I realize I am coming late to the party and the explanation may exist somewhere I haven't seen... 

Overall I am curious whey these platform-specific options couldn't apply to all platforms....
