### ISSUE TITLE
Add support for Metacello configurations

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#25]
Some projects (e.g. [1]) use Metacello configurations instead of baselines and therefore, we should add support for configurations to smalltalkCI.
This is related to #21.

[1] https://github.com/frankshearar/Control

**Comment by fniephaus** [comment]
@frankshearar: I have added [support for Metacello configurations](https://github.com/hpi-swa/smalltalkCI/issues/25) to smalltalkCI today.

Since we are still [discussing how to configure Smalltalk builds in the future](https://github.com/hpi-swa/smalltalkCI/issues/20), a Metacello configuration can only be set via command line parameter at the moment.
So once we have a solution you should probably update your project's configuration once more.

The following should now work for your *Control* project:

```yml
language: smalltalk
sudo: false
smalltalk:
  - Squeak-trunk
  - ...

script: $SMALLTALK_CI_HOME/run.sh --mc-config "Control"
```
