### ISSUE TITLE
Support for GitlabCI

### ISSUE THREAD

**Issue by gcotelli** [hpi-swa/smalltalkCI#262]
I think would be good if smalltalkCI can also run using the Gitlab CI infrastructure in addition to travis and appveyor. As far as I understand GitLab offers free private repos including CI Runners on gitlab.com, and also a Community Edition that can be self-hosted. Checkout https://about.gitlab.com/gitlab-ci/ and https://docs.gitlab.com/ce/ci/README.html

**Comment by fniephaus** [comment]
Hi @gcotelli,
Thanks for the suggestion. It shouldn't be hard to get smalltalkCI running on GitLab's CI infrastructure. I'll have a look when I have some more time. If you get it working before that, feel free to contribute :)

**Comment by peteruhnak** [comment]
I've played around with gitlab and Pharo a bit, and it was very straight-forward, example `.gitlab-ci.yml` (basically I've just extracted commands from here https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/smalltalk.rb )

```yaml
variables:
  DEFAULT_DEPS: "libc6:i386 libuuid1:i386 libfreetype6:i386 libssl1.0.0:i386"
  PHARO_DEPS: "$DEFAULT_DEPS libcairo2:i386"

before_script:
  # Set 32bit and update apt
  - sudo dpkg --add-architecture i386
  - sudo apt-get update -yqq
  # Install dependencies
  - echo "Installing dependencies"
  - sudo apt-get install -y --no-install-recommends $PHARO_DEPS
  # Install smalltalkCI
  - pushd $HOME > /dev/null
  - echo 'Downloading and extracting smalltalkCI'
  - wget -q -O smalltalkCI.zip https://github.com/hpi-swa/smalltalkCI/archive/master.zip
  - unzip -q -o smalltalkCI.zip
  - pushd smalltalkCI-* > /dev/null
  - source env_vars
  - popd > /dev/null
  - popd > /dev/null

stages:
  - build

build:
  stage: build
  script:
    - $SMALLTALK_CI_HOME/run.sh -s "Pharo-6.0"
```

**Comment by fniephaus** [comment]
I also got a `Squeak-trunk` working with the following `.gitlab-ci.yml`:

```yml
before_script:
  - dpkg --add-architecture i386
  - apt-get update -qq
  - apt-get install -y --no-install-recommends curl bsdmainutils wget unzip
  - apt-get install -y --no-install-recommends libc6:i386 libuuid1:i386 libfreetype6:i386 libssl1.0.0:i386
  - wget -q -O smalltalkCI.zip https://github.com/hpi-swa/smalltalkCI/archive/master.zip
  - unzip -q -o smalltalkCI.zip
  - cd smalltalkCI-*; source env_vars; cd

test:
  script:
    - cd $CI_PROJECT_DIR; $SMALLTALK_CI_HOME/run.sh -s Squeak-trunk
```

Still need to work on this a little bit, before we can add a recommendation to the `README.md`.
