### ISSUE TITLE
Coveralls reporting subclassResponsability as not covered

### ISSUE THREAD

**Issue by serpi90** [hpi-swa/smalltalkCI#331]
Using the following configuration
```yaml
language: smalltalk
sudo: false
os:
  - linux
smalltalk:
  - Pharo-stable
  - Pharo64-stable
```

Coverage on the 32 bit build works fine.
Coverage on the 64 bit build reports messages with `self subclassResponsibility` as not being covered.

Can be seen on: https://coveralls.io/builds/13981053
