### ISSUE TITLE
Builds broken due to yaml_parser when `smalltalk` key doesn't map to a list

### ISSUE THREAD

**Issue by Balletie** [hpi-swa/smalltalkCI#39]
Consider the following travis.yml taken from [my project](https://github.com/Balletie/GitHub/blob/49c755736fe49b7d4ae8ca0d71c111b4ec94d819/.travis.yml), which does not work now:

```yaml
language: smalltalk
sudo: false
smalltalk: Pharo-5.0
env:
  global:
    - BASELINE="GitHub"
    - BASELINE_GROUP="tests"
    - PACKAGES="."
```

My builds were working fine up to yesterday. Is the value for `smalltalk` required to be a list now? I got the following error:

```
/home/travis/smalltalkCI-master/yaml_parser.rb:54:in `<main>': undefined method `first' for "Pharo-5.0":String (NoMethodError)
```
