### ISSUE TITLE
[Feature Request] Staging

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/smalltalkCI#431]
Hello,

are there currently any plans to support [Staging on TravisCI](https://docs.travis-ci.com/user/build-stages/)? Or is this already possible?

I would highly welcome this feature for Smalltalk!

**Comment by fniephaus** [comment]
What do you mean by "support staging"? You can use stages and to use smalltalkCI, you'd need to manually call it via `script: smalltalkci`. Example:

```yml
jobs:
  include:
    - stage: test
      script: smalltalkci
    - stage: other
      script: ...
```

Or are you looking for ways to deploy an image after it has passes the tests?

**Comment by LinqLover** [comment]
Hi, sorry for the imprecise description. I was looking for an option to run tests dependent from the current stage. I want to test Smalltalk code and not to write any scripts.

In our project, we have implemented a #longStage pragma which we currently use to defer tests which only shall be executed on Travis CI. Is there a feature to find out the current test stage in smalltalkCI? Ideally, I would like to mark tests with a #stage: pragma and have smalltalkCI run them in different stages.

I am not familiar with the smalltalkCI implementation at all, but here some implementation ideas: smalltalkCI could support a command line option to specify the stage, so I could write

jobs:
  include:
    - stage: default
      script: smalltalkci
    - stage: complete
      script: smalltalkci -stage=complete
    - stage: stress
      script: smalltalkci -stage=stress

A test method could look like the following:

testStress
    <stage: #stress>
    100 timesRepeat: ["some stressing operation"].
    self assertEverythingIsFine.

smalltalkCI could pass the stage argument to the VM process where the TestCase class (or any other CI-specific class) could retrieve it in #addToSuite:fromMethods: to filter the list of tests to be run.

Just some thoughts, I would look forward to your reaction :)
________________________________
Von: Fabio Niephaus <notifications@github.com>
Gesendet: Dienstag, 23. Juli 2019 21:31 Uhr
An: hpi-swa/smalltalkCI <smalltalkCI@noreply.github.com>
Cc: Christoph T. <christoph.thiede@outlook.de>; Author <author@noreply.github.com>
Betreff: Re: [hpi-swa/smalltalkCI] [Feature Request] Staging (#431)


What do you mean by "support staging"? You can use stages and to use smalltalkCI, you'd need to manually call it via script: smalltalkci. Example:

jobs:
  include:
    - stage: test
      script: smalltalkci
    - stage: other
      script: ...

Or are you looking for ways to deploy an image after it has passes the tests?

**Comment by fniephaus** [comment]
Ah, I understand. I like the idea, but right know I'd consider this a very customized setup. At the moment, I'd suggest you split your tests into different packages and use multiple configuration files.
Something like this should work:

```yaml
jobs:
  include:
    - stage: default
      smalltalk_config: .smalltalk-default.ston
    - stage: complete
      smalltalk_config: .smalltalk-complete.ston
    - stage: stress
      smalltalk_config: .smalltalk-stress.ston
```

[Metacello](https://github.com/Metacello/metacello/blob/master/.travis.yml) is doing something similar.

**Comment by LinqLover** [comment]
Thank you for the tip! (Unfortunately, this is quite incompatible with our current testing architecture, where we run the same tests in both stages, but consider only 10% of our fixtures in the short stage.)

**Comment by fniephaus** [comment]
Additionally, you could use [environment variables](https://docs.travis-ci.com/user/environment-variables/) to encode the stage. Then, you can read env vars using `SmalltalkCI getEnv: 'NAME'`. However, this means your code has knowledge about smalltalkCI.

For compatibility, you might want to use something like this:
```smalltalk
Smalltalk globals at: #SmalltalkCI
	ifPresent: [ :sci | (sci getEnv: 'YOUR_VAR') ]
	ifAbsent: [ 'unknown' ]
```

If you prefer a clean dependency, I'd suggest to use [`OSProcess`](http://www.squeaksource.com/OSProcess.html) and `OSProcess thisOSProcess getEnvironmentDictionary` instead.

**Comment by LinqLover** [comment]
Thanks for the tip again. I wrote the following .travis.yml:

```yml
language: smalltalk
sudo: false

os:
  - linux
  - osx

smalltalk:
  - Squeak-5.2
  - Squeak-5.1

jobs:
  include:
    - stage: shortstage
      smalltalk_config: .smalltalk.ston
    - stage: longstage
      smalltalk_config: .smalltalk.ston
```

Unfortunately, Travis runs all four combinations of OS's and Smalltalk versions under the stage "test" and the each only one configuration for the stages "shortstage" and "longstage". How can I tell it to run all configurations in each stage?

**Comment by fniephaus** [comment]
First, you don't need to set `smalltalk_config: .smalltalk.ston` because this is a default. Apart from that, I don't quite understand what combination you are looking for. But I think this could be what you want:

```yml
language: smalltalk
sudo: false

jobs:
  include:
    - stage: shortstage
      os:
        - linux
        - osx
      smalltalk:
        - Squeak-5.2
        - Squeak-5.1
    - stage: longstage
      os:
        - linux
        - osx
      smalltalk:
        - Squeak-5.2
        - Squeak-5.1
```

You might be able to reduce the redundancy using an alias:

```yml
language: smalltalk
sudo: false

aliases:
  - &os-smalltalk-combination
    os:
      - linux
      - osx
    smalltalk:
      - Squeak-5.2
      - Squeak-5.1

jobs:
  include:
    - stage: shortstage
      <<: *os-smalltalk-combination
    - stage: longstage
      <<: *os-smalltalk-combination
```

I haven't tested any of this and it's possible that you cannot avoid the default "test" stage.
