### ISSUE TITLE
Is it possible to run arbitrary commands on a smalltalk VM in the '_builds' directory?

### ISSUE THREAD

**Issue by samWson** [hpi-swa/smalltalkCI#462]
For my use case I'm using smalltalkCI in a Github action because it makes it easy to fetch an image and VM. What I'm also wanting is for a command to be sent to the smalltalk image to build some files for a website from the in image objects. I'm also wanting this build step not to happen if the tests that smalltalkCI runs fail.

Here is my action workflow:
```yaml
name: Build web artifacts
on: [push]

jobs:
  build:
    name: Build web artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout exercism/pharo
        uses: actions/checkout@v2
        with:
          ref: '' # This should default to the branch and reference that triggered the workflow.

      - name: Download smalltalkCI
        id: smalltalkci
        uses: hpi-swa/setup-smalltalkCI@1.1.0
        with:
          smalltalk-version: Pharo64-8.0

      - name: Download Pharo and run tests
        run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-version }}
        shell: bash
        timeout-minutes: 15

      - name: Hello world
        if: ${{ success() }}
        run: "./pharo Pharo.image perform Transcript show: 'Hello world!'"
```

The line `./pharo Pharo.image perform Transcript show: 'Hello world!'` won't work of course because the image and VM are in the `_builds` directory. I want substitute a that line for a 'build files' command. I'm also wanting this step to run only if the tests pass.

I know it is possible to run a post testing script with `SCICustomScript` in the `.smalltalk.ston` but I don't know if it's possible to make the post test hook not run on a test failure. If I'm going to use a post testing hook then I also want a different config file because the `.smalltalk.ston` in my repo is also used for Travis CI.

[Here](https://github.com/exercism/pharo-smalltalk/issues/416) is the issue where I'm keeping track of this problem (branch `github-action-test`). Let me know if this can work or if there is a better way.
