### ISSUE TITLE
Unsupported Squeak version 'Squeak-5.3'.

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/smalltalkCI#483]
Given a CI configuration with implicit image architecture specification like this:

```yml
language: smalltalk

os:
  - linux

smalltalk:
  - Squeak-Trunk
  - Squeak-5.3
  - Squeak-5.2
  - Squeak-5.1
```

smalltalkCI will correctly run the tests for `Squeak-Trunk`, `Squeak-5.2`, and `Squeak-5.1`. However, for `Squeak-5.3`, I reproducibly got this error message instead:

> Starting Squeak build...
> Unsupported Squeak version 'Squeak-5.3'.
> The command "smalltalkci" exited with 1.

See https://travis-ci.org/github/hpi-swa-teaching/SpreadSheetTool/jobs/738761322 https://travis-ci.org/github/hpi-swa-teaching/SpreadSheetTool/jobs/738448351 for example.

[Specifying](https://github.com/hpi-swa-teaching/SpreadSheetTool/commit/721500fd981b24d09d69db988eb84ec30556e887) the image architecture explicitly [solved](https://travis-ci.org/github/hpi-swa-teaching/SpreadSheetTool/jobs/738763250) this issue; however, the behavior is inconsistent and IMHO should be aligned so that `Squeak-5.3` would be interpreted as `Squeak64-5.3` analogously to `Squeak-5.2` etc.
