### ISSUE TITLE
Metacello loading error on GitLab.com CI

### ISSUE THREAD

**Issue by JanBliznicenko** [hpi-swa/smalltalkCI#564]
Hello, I am trying to make GitLab CI working for my project. It is project migrated from GitHub where CI works well.
I created .gitlab-ci.yml and modified .smalltalk.ston, but I get following error loading Metacello:

```
MetacelloNameNotDefinedError: project group, or package named: 'FileTree' not found when used in requires: or 
includes: field of package: 'Metacello-FileTree' for version: baseline of BaselineOfMetacello
```

While on GitHub, it starts with loading baseline of my project, on GitLab, it starts by loading the Metacello (and that results in the error).

This is the full log: https://gitlab.com/JanBliznicenko/openponk/-/jobs/2933194553

This is the .gitlab-ci.yml:

```
image: hpiswa/smalltalkci

variables:
  REPOSITORY_NAME: 'openponk'
  PROJECT_NAME: 'openponk'
  VERSION: 'nightly'
  RUN_ID: $CI_JOB_ID

build-linux:
  stage: build
  variables:
    PLATFORM: 'linux'
  before_script: 
    - "chmod u+x .github/scripts/build-linux.sh"
  script: "smalltalkci -s 'Pharo64-10'; ./.github/scripts/build-linux.sh"
  artifacts: 
    paths:
      - $PROJECT_NAME-$PLATFORM-$VERSION.zip
```

And this is the .smalltalk.ston:

```
SmalltalkCISpec {
	#loading : [
		SCIMetacelloLoadSpec {
			#platforms : [
				#pharo
			],
			#repository : 'gitlab://JanBliznicenko/openponk',
			#baseline : 'OpenPonk',
			#directory : 'repository',
			#load : [ 'default' ]
		}
	],
	#testing : {
		#packages : [
			'OpenPonk*',
			'FileDialog*',
			'SynchronizedLinks*'
		]
	}
}
```
