### ISSUE TITLE
Failing jobs for Pharo32-xx (Linux, MacOs and Windows)

### ISSUE THREAD

**Issue by labordep** [hpi-swa/smalltalkCI#601]
Hi,

I'm trying to execute Pharo32-11 jobs and for all OS I have a job failure.
![image](https://github.com/hpi-swa/smalltalkCI/assets/49183340/d3db69c6-48bd-4b42-885c-0cc58b169973)

Info : this is working fine for Pharo64-11.
![image](https://github.com/hpi-swa/smalltalkCI/assets/49183340/26e76217-727d-4334-a408-94996f736fef)

For Ubuntu : 
![image](https://github.com/hpi-swa/smalltalkCI/assets/49183340/7b1bebfd-d62d-4fbc-aec5-b2543589b9c6)

For MacOS : 
![image](https://github.com/hpi-swa/smalltalkCI/assets/49183340/3e5a395b-c3ac-44ba-9918-be872053e3d1)

For Windows : 
![image](https://github.com/hpi-swa/smalltalkCI/assets/49183340/3bfadcb5-2a04-4030-a5d9-084cab042bdf)

I'm using this script : 

```
name: 'Pharo 11 CI'

on:
  push:
    branches:
      - '**'
      - '!master'
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        smalltalk: [ Pharo64-11, Pharo32-11 ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Load in New Image and Run Tests
        run: smalltalkci -s ${{ matrix.smalltalk }} ${{ matrix.ston }}
        shell: bash
        timeout-minutes: 10
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Thanks for your help :)

**Comment by fniephaus** [comment]
# Linux problem
Could you please try again using `ubuntu-20.04` insteand of `ubuntu-latest`?

# macOS problem
It seems the zeroconfig at https://get.pharo.org/32/110 is broken: it links to https://files.pharo.org/get-files/110/pharoImage-x86.zip but the file now seems to be called https://files.pharo.org/get-files/110/pharoImage-x86**_64**.zip.

@estebanlm could you please take a look?

**Comment by labordep** [comment]
Thanks @fniephaus for your help.

I have tried this script : 

```
name: 'Pharo 11 CI'

on:
  push:
    branches:
      - '**'
      - '!master'
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-latest, windows-latest ]
        smalltalk: [ Pharo64-11 ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Load in New Image and Run Tests
        run: smalltalkci -s ${{ matrix.smalltalk }} ${{ matrix.ston }}
        shell: bash
        timeout-minutes: 10
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

But it doesn't change the used version of linux (22.04) :(
