### ISSUE TITLE
[Question] How to configure merge request trigger on a GitLab server ?

### ISSUE THREAD

**Issue by labordep** [hpi-swa/smalltalkCI#614]
Hi, is anybody know how to configure some rules on a GitLab server ?
I'm using gitlab configuration of SmalltalkCI.
On GitHub there is a script way to configure Actions and define trigger on PR, commit, branches, etc. 
I haven't found this equivalent for GitLab, for example: 
```
on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [assigned, opened, synchronize, reopened]
```

To be more concrete, I don't know how to configure my project to execute CI on specific branches (for exemple 'main' and 'dev') and how to configure the CI to execute tests when a merge request is opened.

Thanks.
